name: quantum-env 
channels:
  - defaults
dependencies:
  - python=3.11.5
  - pip:
      - qiskit==1.3.2
      - qiskit-aer==0.15.0
      - qutip==5.0.4
      - pylatexenc==2.10
      - sympy==1.13.2
      - python-dotenv
      - numpy
      - pandas
      - matplotlib 
      - plotly
      - scipy
